<h1 style="color:red;">What is Pytorch?</h1> 

    
 PyTorch is a tool that helps you build and train computer models to recognize patterns, like identifying objects in images or understanding language. PyTorch defines a class called Tensor (torch.Tensor) to store and operate on homogeneous multidimensional rectangular arrays of numbers.rch!

In [1]:
import torch
x= torch.empty(2,3)
x

tensor([[-6.7799e-09,  3.0756e-41, -6.7759e-09],
        [ 3.0756e-41,  1.1210e-43,  0.0000e+00]])

In [2]:
y=torch.rand(2,3)
y

tensor([[0.9574, 0.8304, 0.7130],
        [0.0809, 0.5707, 0.8176]])

In [3]:
z=torch.rand(2,3)
z

tensor([[0.4426, 0.8664, 0.3959],
        [0.9920, 0.9242, 0.0803]])

In [4]:
#We can also specify the data type
m=torch.ones(2,3, dtype=torch.float64)
m.dtype

torch.float64

In [5]:
y+z

tensor([[1.4000, 1.6968, 1.1089],
        [1.0729, 1.4949, 0.8979]])

In [6]:
torch.add(y,z)

tensor([[1.4000, 1.6968, 1.1089],
        [1.0729, 1.4949, 0.8979]])

In [7]:
y.add_(z)

tensor([[1.4000, 1.6968, 1.1089],
        [1.0729, 1.4949, 0.8979]])

In [8]:
y-z

tensor([[0.9574, 0.8304, 0.7130],
        [0.0809, 0.5707, 0.8176]])

In [9]:
torch.sub(y,z)

tensor([[0.9574, 0.8304, 0.7130],
        [0.0809, 0.5707, 0.8176]])

In [10]:
torch.mul(y,z)

tensor([[0.6196, 1.4700, 0.4390],
        [1.0644, 1.3815, 0.0721]])

In [11]:
# Lets print all the rows but one column and similarly all the column with 1 row
k=torch.rand(5,3)
print(k)
print(k[:,1:])
print(k[:,[0]])

tensor([[0.6463, 0.2005, 0.7957],
        [0.0374, 0.9845, 0.4592],
        [0.9075, 0.4644, 0.7022],
        [0.5143, 0.9499, 0.2334],
        [0.7156, 0.5222, 0.1222]])
tensor([[0.2005, 0.7957],
        [0.9845, 0.4592],
        [0.4644, 0.7022],
        [0.9499, 0.2334],
        [0.5222, 0.1222]])
tensor([[0.6463],
        [0.0374],
        [0.9075],
        [0.5143],
        [0.7156]])


In [12]:
# We can get the actual value of the particular row and column we can use .item()
k[0,0].item()

0.6462954878807068

In [13]:
#convert a tensor into numpy array
import numpy as np
a= torch.ones(1,5)
b= a.numpy()
a


tensor([[1., 1., 1., 1., 1.]])

In [14]:
b

array([[1., 1., 1., 1., 1.]], dtype=float32)

In [15]:
#Convert a numpy array to a tensor
c=np.ones(5)
d=torch.from_numpy(c)
d

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)

In [16]:
# sometimes when the tensor is defined there is an argument requires_grad=True, by default it is false, it helps in optimization later on
e=torch.ones(3,4, requires_grad=True)
e

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]], requires_grad=True)

<span style="color:#FF5733">This section will talk about the autograd and how we can calculate gradients from it. Gradient is important for optimization. 

In [17]:
x1=torch.randn(3, requires_grad=True)
x1

tensor([0.7178, 0.9327, 1.1487], requires_grad=True)

<span style="color:blue">The requires_grad=True argument tells PyTorch that we want to compute gradients with respect to this tensor during backpropagation

In [18]:
y1=x1+2
y1

tensor([2.7178, 2.9327, 3.1487], grad_fn=<AddBackward0>)

<span style="color:blue">grad_fn tells you that y1 was created by an addition operation, and PyTorch has recorded this operation as part of the computation graph enabling PyTorch to efficiently compute gradients

In [19]:
y2=x1*x1*2
y2

tensor([1.0304, 1.7400, 2.6389], grad_fn=<MulBackward0>)

In [20]:
y3= y2.mean()
y3

tensor(1.8031, grad_fn=<MeanBackward0>)

<span style="color:blue">To calculate the gradient, all we need to now do is y3.backward() which will do dy3/dx1.. For scalar , no argument is needed but for vector we need to put the argument as same size as x1 

In [21]:
#y3.backward() # for scalar


In [22]:
v= torch.tensor([0.1,0.02,0.003], dtype=torch.float32)
y2.backward(v) #for vector

In [23]:
x1.grad

tensor([0.2871, 0.0746, 0.0138])

<span style="color:blue">Let's say now that we don't want the requires_grad=true, so that pytorch wont track the history in computational graph: 
We essentially have three options: 
1) x1.requires_grad_(False), remember that whenever there is underscore _ it will modify the variable in place
2) x.detach()
3) with torch.no_grad()

In [24]:
x1.requires_grad_(False)
x1

tensor([0.7178, 0.9327, 1.1487])

In [25]:
y2.detach()


tensor([1.0304, 1.7400, 2.6389])

<span style="color:blue">Let's look at the trainning iteration where we want to make sure that for each iteration the x1.grad computes the same value. It is done by setting the grad value to zero after each iteration.

In [26]:
weights=torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)

tensor([3., 3., 3., 3.])
tensor([6., 6., 6., 6.])
tensor([9., 9., 9., 9.])


In [27]:
weights=torch.ones(4, requires_grad=True)
for epoch in range(3):
    model_output=(weights*3).sum()
    model_output.backward()
    print(weights.grad)
    weights.grad.zero_()

tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])
tensor([3., 3., 3., 3.])


<span style="color:red"> Backpropagation

In [28]:
import torch
x=torch.tensor(1.0)
y=torch.tensor(2.0)

w=torch.tensor(1.0, requires_grad=True)

#Forward pass and  compute the loss
y_hat=w*x
loss=(y_hat-y)**2

print(loss)

#Backward pass

loss.backward()
print(w.grad)

## update weights



tensor(1., grad_fn=<PowBackward0>)
tensor(-2.)


# Homework #1

Please use the above information to do the following things:

## **Tensor Operations:**
1. **Create a 4x4 tensor with random values.**
2. **Add a tensor of ones to this tensor and then multiply the result by 2.**
3. **Extract the second column from the resulting tensor.**

## **Conversion between Tensor and NumPy Array:**
1. **Create a tensor of size (2, 4) filled with ones and convert it to a NumPy array.**
2. **Modify the tensor so that it no longer requires gradient computation.**

## **Gradient Computation:**
1. **Define a 2x2 tensor with `requires_grad=True`.**
2. **Perform a simple operation like addition or multiplication on this tensor.**
3. **Compute the mean of the resulting tensor.**
4. **Calculate the gradient with respect to the original tensor using the `.backward()` method.**

## **Backpropagation and Weight Updates:**
1. **Simulate a simple training loop for 4 epochs where the model predicts a value based on a weight.**
2. **Initialize the weight as 1.0 with `requires_grad=True`.**
3. **For each epoch, compute the loss, backpropagate the gradients, and update the weight.**
4. **Print the weight gradients after each epoch.**
5. **Ensure that the gradients are reset to zero after each update.**
